const data = {
  plugins: [
    {
      plugin: "click",
      description: "allows you to click on screen",
      author: "John Smith",
      icon: "",
    },
    {
      plugin: "fise",
      description: "",
      author: "Jane Smith",
      icon: "",
    },
    {
      plugin: "puns",
      description: "one liner jokes",
      author: "Steve Smith",
      icon: "",
    },
    {
      plugin: "time",
      description: "skills about fetching times",
      author: "",
      icon: "",
    },
    {
      plugin: "weather",
      description: "skills regarding getting fetching the weather",
      author: "Lara Smith",
      icon: "",
    },
    {
      plugin: "main",
      description: "general hello and goodbye skills",
      author: "",
      icon: "",
    },
  ],
  skills: [
    {
      plugin: "click",
      category: "miscellaneous",
      description: "simulate a left click",
      examples: [
        "click",
        "click!",
        "click please",
        "please click",
        "click the mouse",
      ],
    },
    {
      plugin: "fise",
      category: "miscellaneous",
      description: "change the background",
      examples: [
        "change the background",
        "change the background please",
        "please could you change the background?",
        "could you change the background?",
        "change my background",
        "change my background please",
        "please could you change my background?",
        "could you change my background?",
      ],
    },
    {
      plugin: "fise",
      category: "miscellaneous",
      description: "call another user via video conferencing",
      examples: [
        "call Daniel",
        "please could you call Tim",
        "please could you call James for me",
        "I would like to speak to Albert",
        "I'd like to speak to Simon",
        "video call David",
        "video call David please",
      ],
    },
    {
      plugin: "puns",
      category: "miscellaneous",
      description: "tell a joke",
      examples: [
        "tell me a joke",
        "tell me a joke please",
        "tell me a dad joke",
        "tell me a dad joke please",
        "tell me a pun",
        "tell me a pun please",
        "give me a joke",
        "give me a joke please",
        "give me a dad joke",
        "give me a dad joke please",
        "give me a pun",
        "give me a pun please",
        "could you please tell me a joke?",
        "could you tell me a joke?",
        "I'd love to hear a joke",
        "I'd love to hear a dad joke",
        "I'd love to hear a pun",
        "give me your cheesiest joke",
        "give me a cheesy joke",
        "tell me a cheesy joke",
        "tell me something funny",
      ],
    },
    {
      plugin: "puns",
      category: "miscellaneous",
      description: "assure the user of the quality of dad jokes",
      examples: [
        "Are you funny?",
        "How funny are you?",
        "How good are your puns?",
        "How good are your dad jokes?",
        "How cheesy are your jokes?",
      ],
    },
    {
      plugin: "time",
      category: "miscellaneous",
      description: "give the system time",
      examples: [
        "What time is it?",
        "What time is it right now?",
        "What time is it now?",
        "Tell me the time",
        "Tell me the time right now",
        "Tell me the time now",
      ],
    },
    {
      plugin: "weather",
      category: "miscellaneous",
      description: "give the weather at a given location",
      examples: [
        "what is the weather in Manchester?",
        "what's the weather in Leeds?",
        "what's the temperature in London?",
        "what's the temperature in Bloomsbury right now?",
        "how hot is it in New York?",
        "how cold is it in Oslo?",
      ],
    },
    {
      plugin: "main",
      category: "miscellaneous",
      description: "Greet the user",
      examples: ["Hello", "Hi", "Hey", "Howdy", "Howdy, partner"],
    },
    {
      plugin: "main",
      category: "miscellaneous",
      description: "Say goodbye to the user.",
      examples: [
        "Goodbye",
        "Good bye",
        "Bye",
        "Bye bye",
        "See you",
        "See you later",
        "In a bit!",
        "Catch you later!",
      ],
    },
  ],
};

export default data;
